
site_name: Curadoria do Profmat
site_url: https://mathtech-cefet-mg.github.io/Curadoria_Profmat/

nav:
  - Início:          index.md
  - Por ano:         pages/years.md
  - Por instituição: pages/schools.md
  - Em números:      numbers/numbers.md
  - Editores:
    - Luis A. D'Afonseca: pages/editors/luis.md
    - Larissa:            pages/editors/larissa.md

theme:
  name:       material
  language:   pt-BR
  logo:       imag/favicon.png
  favicon:    imag/favicon.png
  custom_dir: docs/overrides

  features:
    - navigation.instant
    - content.code.copy

  font:
    text: "Lato"
    code: "Fira Code"

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true # Enables dollar delimiters for inline math

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - stylesheets/extras.css

extra:
  analytics:
    provider: google
    property: G-YKYZH0QLD2
